language: cpp

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

compiler:
  - clang
  - gcc

env:
  global:
   - CMAKE_VERSION=3.14.7
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "g6juqk/pIJTlmM+8aOAO69Pu3nze7uEifn58DtqG/9CKUlRSjnhAqG9EO7UyH1z0GnAEDj/ZRHFiAycYv9tLcFhzhOYCTiYUl4d7PwSd5vS1liDgfrQJNtdR1W2oqr+wVt8g3sReGBbgUlMrGu6fP3G8Xsv1OOj5mFR/LxVECXI="

cache:
  directories:
  - $HOME/deps
  - $HOME/Library/Caches/Homebrew

install:
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd "${DEPS_DIR}"
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ] ; then
        CMAKE_ARCH="Linux-x86_64"
        CMAKE_DIR="cmake-${CMAKE_VERSION}-${CMAKE_ARCH}"
        CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/${CMAKE_DIR}.tar.gz"
        if [[ ! -e "${CMAKE_DIR}" ]] ; then
          rm -rf cmake-*
          mkdir "${CMAKE_DIR}"
          travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar -xz
        fi
        export PATH="${DEPS_DIR}/${CMAKE_DIR}/bin:${PATH}"
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ] ; then export PATH="/usr/local/opt/qt5/bin:${PATH}" ; fi
  - cd ${TRAVIS_BUILD_DIR}

addons:
  apt:
    packages:
      - qtbase5-dev
      - qttranslations5-l10n
  homebrew:
    packages:
    - qt
  coverity_scan:
    project:
      name: "stepping-stone/sepiola"
      description: "Build submitted via Travis CI"
    notification_email: info@stepping-stone.ch
    build_command: "make"
    branch_pattern: coverity_scan

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi

matrix:
  exclude:
  # Ignore gcc on macOS since it's a symlink to clang (alternative: make cmake pick up g++ from homebrew)
  - os: osx
    compiler: gcc
